from opengl.gl.raw.gl_1_0 import *
from opengl.gl.raw.gl_1_1 import *
from opengl.gl.raw.gl_1_2 import *
from opengl.gl.raw.gl_1_3 import *
from opengl.gl.raw.gl_1_4 import *
from opengl.gl.raw.gl_1_5 import *
from opengl.gl.raw.gl_2_0 import *
from opengl.gl.raw.gl_2_1 import *
from opengl.gl.raw.gl_3_0 import *
from opengl.gl.raw.gl_3_1 import *
from opengl.gl.raw.gl_3_2 import *
from opengl.gl.raw.gl_3_3 import *
from opengl.gl.raw.gl_4_0 import *
from opengl.gl.raw.gl_4_1 import *
from opengl.gl.raw.gl_4_2 import *
from opengl.gl.raw.gl_4_3 import *
from opengl.gl.raw.gl_4_4 import *
from opengl.gl.raw.gl_4_5 import *
from opengl.gl.raw.gl_es_cm_1_0 import *
from opengl.gl.raw.gl_es_2_0 import *
from opengl.gl.raw.gl_es_3_0 import *
from opengl.gl.raw.gl_es_3_1 import *
from opengl.gl.raw.gl_es_3_2 import *